In [1]:
import torch
import numpy as np

In [3]:
# automatic differentiation on tensors
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()
print(x)
print(y)
print(z)
print(out)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [4]:
y.retain_grad()
z.retain_grad()
out.backward()

In [5]:
print(z.grad)
print(y.grad)
print(x.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [6]:
# efficient inference with torch.no_grad(when gradient calculation is not required)
with torch.no_grad():
    x = torch.ones(2, 2, requires_grad=True)
    y = x + 2
    z = y * y * 3
    out = z.mean()
print(x)
print(y)
print(z)
print(out)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]])
tensor([[27., 27.],
        [27., 27.]])
tensor(27.)


In [7]:
out.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn